### ISSUE TITLE
GUI front-end

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/kotnetcli#111]
I have created a simple Qt GUI front-end (`dev-gui` branch) that runs a kotnetcli Worker in a background thread and  employs a custom communicator to translate netlogin progress calls to Qt signals, connected to the main GUI thread.

Basic interface looks as follows, but needs further polishing. Help/suggestions are welcome...

![kotnetgui](https://cloud.githubusercontent.com/assets/2464627/15088409/8e98510c-13f3-11e6-8774-a5ef0c7db655.png)

**Comment by jovanbulck** [comment]
@GijsTimmers could you have a look at the packaging via `setup.py`? After installation a `kotnetgui` shell command should be available. Or even better: a `.desktop` entry?

**Comment by GijsTimmers** [comment]
Definitely.

**Comment by jovanbulck** [comment]
Done! e443ae6a3a29a860747719ce6719c0fb1f0619a5
