### ISSUE TITLE
Store institution choice in credentials

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/kotnetcli#114]
Proposal: same user will always login with the same institution, so we might as well remember the choice and store it alongside username/pwd in the `Credentials` back-end. When prompting the user for credentials the first time, or in guest mode, the institution name should also be queried.

This is easier and more elegant than passing a command line option, or configuring an alias to do so.

**Comment by GijsTimmers** [comment]
First off, good idea. This will be useful in most cases, but not always.

See also #113. Suppose that a user takes his laptop to a library or another KU Leuven building. Also suppose that he hasn't configured his laptop to connect to eduroam and he wants to connect to kuleuven-guest instead. In that case, he'd have to use guest-mode which is a bit strange.

Proposal: store institution choice in credentials, but allow it to be overridden by the `--institution` flag.

**Comment by jovanbulck** [comment]
Done!

**Comment by GijsTimmers** [comment]
Haha great stuff!
