### ISSUE TITLE
Either use curses.wrapper() to end gracefully with exceptions or write a scherm.terminate() and put it in each exception.

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#18]
When you end `kotnetcli` with an exception, your terminal gets messy. We can avoid that by using `curses.wrapper(YourCursesMethod())`, but that's not so easy here.

Another way to do it would be to to write a `scherm.terminate()` method and put that in each exception catch. That's easy, but dirty.

**Comment by jovanbulck** [comment]
As the `beeindig_sessie()` method is now called from the worker as you sketched above, I think this issue can be closed

**Comment by GijsTimmers** [comment]
Sure, no problem.
