### ISSUE TITLE
Abstract Credentials

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/kotnetcli#53]
Credentials moeten geabstraheerd worden; **goals**:
- ander credential behavior moet ingeplugd kunnen worden: keyring, guest, dummy, ... zijn gewoon andere implementaties van dezelfde **abstracte interface** / superklasse (bv saveCred, getCred, hasCred, forgetCred). Eventuele toek credentialsystemen met encryptie ofzo kunnen dan ook gewoon inglugd worden
- gebruikersnaam en wachtwoord moeten niet plaintext doorheen de applicatie worden doorgegeven: **geef de instantie van de credentialsklasse door** en vraag daaraan het ww als nodig
- **user input** moet *niet* in de credential klasse worden uitgevoerd, maar in `kotnetcli.py`, zodat alle user input, 'de command line interface' daar geencapsuleerd is. Een eventuele alternatieve implementatie die de gebruikersnaam en wachtwoord via een gui opvraagt, is dan ook daar mogelijk (evt via subklasse die methode override)

Geschetste flow van `kotnetcli.py`:

1. eerst switchen op credential vlaggen, om:
 - maak juiste `credential` klasse aan: `KeyRingCred`, `GuestCred` or `DummyCred`
 - voer eventuele user input (*alle* user input moet in `kotnetcli` geencapsuleerd zijn) uit:
    - --guest-mode: vraag creds aan user, saveCreds() (in de GuestCreds klasse)
    - !hasCred(): vraag creds aan user, saveCreds() (in de keyringCreds klasse)
    - --forget: forgetCreds() en exit

2. dan switchen op actie-typen vlaggen, dan:
 - maak juiste `worker` (== director) instantie aan
 - maak juiste `CommunicatorFabriek` klasse aan

3. Dan, switchen op communicator related vlaggen:
 - maak juiste communicator aan mbv `CommunicatorFabriek` klasse

4. Dan alles in gang zetten:
  - `worker.go(creds, co)`

Zoals merkbaar is `kotnetcli` dan uiteindelijk een cohesieve, mooie klasse die zich alleen bezig houdt met het parsen van zijn user input vlaggen en de zaak op te starten :-) Door die loskoppeling wordt bv. een `gui` / alternatieve cli / android app front-end dan vrij triviaal :+1:

**Comment by jovanbulck** [comment]
done :-)

note: uiteindelijk zijn guest creds niet geïmplementeerd als een eigen klasse, maar als optionele velden in de twee implementaties (dummy en keyring) om het subclassen van kotnetcli_test te vergemakkelijken; zie 226b56c4e250af02b0f8e9db43e0fcdd05878cad

merk ook op dat de browser de creds niet rauw opslaat, maar pas uit het creds object haalt waar nodig

**Comment by GijsTimmers** [comment]
Merci, ik kijk hier zsm naar.
