### ISSUE TITLE
Elegant logging using the logging module

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#59]
Debug stuff like `ik wil bellen blazen` should be elegantly logged using the python [logging](http://victorlin.me/posts/2012/08/26/good-logging-practice-in-python) module.

We will work on this when kotnetcli 2.0.0 is released.

**Comment by jovanbulck** [comment]
implemented basic idea, linked above; added `--debug` option (toggled on by default in `kotnetcli_test.py`)

![screenshot from 2015-02-13 16 57 49](https://cloud.githubusercontent.com/assets/2464627/6190423/265efd46-b3a2-11e4-8a54-287370b8b984.png)
![screenshot from 2015-02-13 16 59 50](https://cloud.githubusercontent.com/assets/2464627/6190424/28015dba-b3a2-11e4-9149-ab3b71be462e.png)

**Comment by GijsTimmers** [comment]
Exactly. Nice job!

**Comment by jovanbulck** [comment]
note: whereas logging of setup-errors (eg import failed or so) is fine, we should not use the logging system to provide users with login-procedure (i.e. `worker`) errors (as I did in the above commits)

Instead, we should think about changing the communicator API with error feedback methods

**Comment by GijsTimmers** [comment]
Yes, just use the communicator for _expected_ errors, and use the logging module for more detail on what's happening.

**Comment by jovanbulck** [comment]
> Yes, just use the communicator for expected errors, and use the logging module for more detail on what's happening.

Done #106
