### ISSUE TITLE
Create a systemd service file to run kotnetcli as a startup script

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#61]
When an Arch user boots his computer, `systemd` services are executed. It would be nice to create one for kotnetcli, for a seamless Kotnet login. An Arch user should run:

    sudo systemd enable kotnetcli.service

to enable this startup script.

[Ubuntu will be moving to systemd as well](http://www.markshuttleworth.com/archives/1316), so the core developers won't put effort in creating `upstart` scripts. That doesn't mean we don't allow these scripts; just open up a pull request if you've created one yourself and we'll gladly merge it.

**Comment by GijsTimmers** [comment]
Some things to take in consideration:
- Is the `systemd` service files directory the same across distributions? If it is, we could create a script to put it in the right directory automatically. Pinging @jovanbulck.
- The `systemd` file should be run with a `--timeout` flag so that it does not slow down the boot time too much. Imagine the Kotnet servers are slow - your boot time might be increased by 30 seconds or something. Pinging @jovanbulck.

**Comment by jovanbulck** [comment]
Good points; some thoughts:

While [accessing systemd from python](https://github.com/systemd/python-systemd) seems to be fairly easy, I believe launching `kotnetcli` this early is neither *possible*, nor *desirable*:

- As you correctly identified above, `kotnetcli` depends on the desktop environment's **keyring**. As far as I can tell, it is not available this early in the booting phase. This makes sense, when considering that is should only be available after the user has successfully logged in (and maybe explicitly unlocked his keyring).
- Moreover, as you again correctly indicate above, `kotnetcli` is too heavy-weighted and non-deterministic. As such, it might well introduce buggy behavior and unacceptable delays...

Summarized, `systemd` should in my opinion only be used for things that are (i) common for the entire system (i.e. not user-specific), and (ii) relatively lightweight. Currently, `kotnetcli` is neither of those.

Of course, the user could add `kotnetcli` to the **auto-start applications** for his or her specific desktop environments. (As far as I can tell, this would not require additional support from our side. Meaningful exit codes, as discussed in issue #55, will of course help shell-scripting users.)

**Comment by GijsTimmers** [comment]
Agreed.
