### ISSUE TITLE
Waar haalt Kotnetforceer() zijn methodes vandaan?

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#62]
We moeten even overleggen over `Kotnetforceer()`. Kijk even naar 512ae35e710635c82a8befc5561633a6dded9dde.

`Kotnetforceer()` heeft veel methodes gemeenschappelijk met `Kotnetlogin()` en `Kotnetlogout()`. We willen die niet opnieuw schrijven, dus laten we `Kotnetforceer()` deze methodes  overerven:

```python
class Kotnetforceer(Kotnetlogin, Kotnetlogout):
...
```

Het probleem is dat zowel `Kotnetlogin()` als `Kotnetlogout()` een methode `resultaten()` bevatten, welke ook beide andere code bevatten.

Mijn voorstel is om `resultaten()` van naam te veranderen in beide klassen, zodat het voor `Kotnetforceer()` duidelijk is, welke `resultaten()` opgevraagd worden:

```python
class Kotnetforceer(Kotnetlogin, Kotnetlogout):
    def go(self):
        ## IP van uit te loggen apparaat opzoeken
        self.netlogin()
        self.kuleuven()
        self.gegevensinvoeren()
        self.gegevensopsturen()
        self.oudipophalen()
        ## Uitloggen
        self.formulieraanmaken()
        self.formulieropsturen()
        self.logoutresultaten() ## dit bedoel ik
        self.netlogin()
        self.kuleuven()
        self.gegevensinvoeren()
        self.gegevensopsturen()
        self.loginresultaten() ## dit bedoel ik
```
Een alternatief wat volgens mij ook werkt, is het expliciet oproepen van deze methodes, zonder de naam te veranderen:

```python
class Kotnetforceer(Kotnetlogin, Kotnetlogout):
    def go():
        ## IP van uit te loggen apparaat opzoeken
        self.netlogin()
        self.kuleuven()
        self.gegevensinvoeren()
        self.gegevensopsturen()
        self.oudipophalen()
        ## Uitloggen
        self.formulieraanmaken()
        self.formulieropsturen()
        Kotnetlogout.resultaten() ## dit bedoel ik
        self.netlogin()
        self.kuleuven()
        self.gegevensinvoeren()
        self.gegevensopsturen()
        Kotnetlogin.resultaten() ## dit bedoel ik
```

Overigens ben ik zeker voorstander van een andere, properdere oplossing. Misschien iets met gedeelde methodes in `SuperWorker()`, bijvoorbeeld.

**Comment by jovanbulck** [comment]
ziet er goed uit :-)

ik vind u tweede oplossing de beste: gewoon dubbel overerven en dan bij name conflict expliciet oproepen. Dat moet werken idd

**Comment by jovanbulck** [comment]
ik ben voor de eerste optie gegaan, zie 597778b9eaede42fdf5a3b5c173c72d2c6b055aa

zou moeten lukken als de browser werkt...

**Comment by jovanbulck** [comment]
mag dicht denk ik; kotnetforceer is voorlopig uitgesteld en het probleem hier is al opgelost in bovengelinkte commit

**Comment by GijsTimmers** [comment]
Ok
