### ISSUE TITLE
We can skip KU Leuven kiezen... by directly jumping to the credentials page.

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#63]

**Comment by jovanbulck** [comment]
works nicely in the above commit with the extra line

``NETLOGIN_URL = "https://netlogin.kuleuven.be/cgi-bin/wayf2.pl?inst=kuleuven&lang=nl&submit=Ga+verder+%2F+Continue"``

**Comment by GijsTimmers** [comment]
This should've been a commit for 3.0.0, but I really like the code, so we're keeping it.
