### ISSUE TITLE
We should consider adding a timeout if we're running on Windows

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#71]
Let's assume that most Windows users will use one of our precompiled binaries, without specifying a Communicator.

When you run such a binary, a console will pop up, and it will log you in to KotNet. When the last mesage has printed in the console, [the console will close immediately](https://vid.me/ozWA). That means that it's hard to take notice of the current upload/download balance. 

Of course, we could write a Qt-based communicator to overcome this. But until we've done that, we should consider writing a timeout. This timeout would require an if-else statement, checking for the OS. We need to put this somewhere. I'd rather not mess up `beeindig_sessie()` with an if-else-statement. Maybe we can create a `SuperBeeindigSessie()` and different subclasses?

**Comment by jovanbulck** [comment]
As discussed, we'll implement this as a separate front-end without options (for non-powerusers); it just executes the login procedure with a ColoramaCommunicator and catches the `SystemExit` exceptions to wait some time before exiting

This allows a functional Windows-binary not to be executed from a shell, without messing up the code base

**Comment by jovanbulck** [comment]
note that the windows terminal login behavior can be simulated with `gnome-terminal -e ./kotnetcli-win-easy.py` on GNOME Linux distros
