### ISSUE TITLE
Define the exception in browser.py

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#75]
Line 82:

    except:
        return False

In its current form, we get a `False` on _every possible_ exception. This is not the desired behaviour. For instance, `KeyboardInterrupt` exceptions should be caught in `worker.py` or `kotnetcli.py`, not all the way down in `browser.py`.

Fix: please check, which exceptions we can ex**pec**t when creating a TCP connection, and catch only those.

**Comment by jovanbulck** [comment]
good catch ;-)
done

**Comment by GijsTimmers** [comment]
Thank you!
