### ISSUE TITLE
Create separate classes for separate tasks in the app, just like in the compurter program.

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#76]
We should have at least:

- `AppBrowser()`
- `AppCredentials()`
- `AppCommunicator()`

and to make everything work together smoothly, our beloved `AppWorker()`.

As much as I'd like the app to just import everything it needs from the 'normal' `browser.py`, `fabriek.py`, etcetera, this is not possible at the moment: the compiled APK file crashes when run on mobile devices. That's why we have to re-write everything we need into the app file.

**Comment by jovanbulck** [comment]
> As much as I'd like the app to just import everything it needs from the 'normal' browser.py, fabriek.py, etcetera, this is not possible at the moment: the compiled APK file crashes when run on mobile devices. That's why we have to re-write everything we need into the app file.

I see it's difficult, but I don't believe copy pasting our code into the android app is a good solution. We should start working on the real problem so that the backend can be imported in the kivy app; see issue #39
