### ISSUE TITLE
Move fabriek.py's contents to __init__.py

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#78]
Before going any further, please read [this article](http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html) first (~450 words).

As said in #77 , I'd like to move to a project in which `__init__.py` contains all stuff that's expected to be imported from that directory (or _package_).

Currently, `fabriek.py` makes sure that the right communicator is built and passed to `kotnetcli.py`.

I propose to move everything in `fabriek.py` to `__init__.py`:

Current situation:

    from communicator.fabriek import LoginCommunicatorFabriek, LogoutCommunicatorFabriek

Proposed situation:

    from communicator import LoginCommunicatorFabriek, LogoutCommunicatorFabriek

This should also resolve strange bugs that we're getting when trying to distribute with `setup.py`, as mentioned in #77 .

@jovanbulck : Please let me know your thoughts about this.

**Comment by jovanbulck** [comment]
>Currently, fabriek.py makes sure that the right communicator is built and passed to kotnetcli.py.
> I propose to move everything in fabriek.py to __init__.py

What exactly do you mean here? I totally agree with using `__init__.py` to simplify `import` statements as you illustrate above and in issue #77 

The title seems to suggest however that you want to move the `fabriek.py` *contents* (i.e. class implmentations) to `__init__.py`? That won't work I think.

**Comment by GijsTimmers** [comment]
I do want to move its contents to `__init__.py`. `fabriek.py` has to do only simple things: create a communicator, and pass it to the worker. I believe that this is possible, let me look at it.

**Comment by jovanbulck** [comment]
> fabriek.py has to do only simple things: create a communicator, and pass it to the worker. I believe that this is possible, let me look at it.

I don't think it is possible nor elegant. Firstly, the importing and creation of a communicator happens *at runtime* (in contrast to `__init__.py` which is processed when the python interpreter is started, I think). Moreover fabriek does indeed only simple thinks, which makes it an elegant and cohesive solution (in contrast to 'magically' trying to move it into __init__ I think)

**Comment by GijsTimmers** [comment]
You're right.
