### ISSUE TITLE
Directory structure and remove depricated files

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/kotnetcli#79]
We'll have to think about how to organize the source tree, I think. This will make browsing the source more easily and will also make the import statements more elegant, as discussed in issue #77 

We now have a `kotnetcli` folder that contains the source code? This has probably something to do with packaging the android app?

I propose the following more or less (See also the general idea in pull request #67); don't know how feasible it is:

```
/
|__ .gitignore
|__ .travis
|__ CONTRIBUTING
|__ LICENSE
|__ README
|__ (maybe symbolic links to the different front-ends in the src folder (eg kotnetcli, kotnetcli-test, kotnetcli-app, ...)
|__ doc
     |__ ...
|__ compile
     |__ ...
|__ src
     |__ kotnetcli.py
     |__ kotnetcli_test.py
     |__ kotnetcli-app.py
     |__ back-end
          |__ *.py
          |__ communicator
               |__ ...
          |__ tools
               |__ ...
```

Moreover, I see some depricated files, which should probably be removed: `kotnetcli-android.py`, `app` directory, `juiste_verbindingen.py`

**Comment by GijsTimmers** [comment]
Hi, thanks for writing this. Some pointers here:

- The separate `kotnetcli` folder is needed to properly package `kotnetcli` for `PyPI` (and thus `pip`), which would be interesting. `distutils` and `setuptools` are used a lot in Python projects to create nicely installable packages. Stuff like `setup.py` (an installation/packaging script) should be one level above the actual application.
- The application directory should be called `kotnetcli` to be properly distributed as a package. So I propose to move directories like `src`, `doc` and `compile` into the `kotnetcli` directory.
- I agree that the deprecated files should be removed.

**Comment by jovanbulck** [comment]
Ok good points, then we indeed do something as:

```
/
|__ .gitignore
|__ .travis
|__ (maybe symbolic links to the different front-ends in the src folder (eg kotnetcli, kotnetcli-test, kotnetcli-app, ...)
|__ CONTRIBUTING
|__ LICENSE
|__ README
|__ kotnetcli
     |__ doc
          |__ ...
     |__ compile
          |__ ...
     |__ src
          |__ kotnetcli.py
          |__ kotnetcli_test.py
          |__ kotnetcli-app.py
          |__ back-end
               |__ *.py
               |__ communicator
                    |__ ...
               |__ tools
                    |__ ...
```

**Comment by GijsTimmers** [comment]
I'd like to comment here again. I have some experience with PyPI and `setuptools` now, and I think that the first design you proposed is doable, and the clearest. The root directory will also contain `kotnetcli-runner.py`, because we need that one when using package design. `testsuite.py` will probably land up here, as well.

So it will look kind of like this:

```
/
|__ .gitignore
|__ .travis
|__ CONTRIBUTING
|__ LICENSE
|__ README
|__ kotnetcli-runner.py
|__ doc
     |__ ...
|__ compile
     |__ ...
|__ src
     |__ kotnetcli.py
     |__ kotnetcli_test.py
     |__ kotnetcli-app.py
     |__ back-end
          |__ *.py
          |__ communicator
               |__ ...
          |__ tools
               |__ ...
```

**Comment by GijsTimmers** [comment]
94bc5cf3f5deb285526c276e52ce1ccd92ca367a

**Comment by GijsTimmers** [comment]
Please remove your local `origin/restructured_init` branch (if any). All the work I was planning to do in that branch has been done in `dev`, so it's pointless to keep. I removed the remote branch already.

**Comment by GijsTimmers** [comment]
I think that we've made enough progress to close this one. Please re-open if you disagree.
