### ISSUE TITLE
Please add to RC codes: 301 for server side internal script error

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#80]
Snippet:

```html
<H1>Resultaat Netwerk Login</H1>
<!-- weblogin: rc=301 -->
<HR>
                <FONT size="+2" color="red">Login NIET geslaagd</FONT><P>
                <B>301</B> : internal script error
		<BR>()
            <HR size=1 noshade>
            <P>
            <TABLE border=1 align="center" width="80%">
            <TR>
            <TD bgcolor="#6666cc">
            <FONT color="white" face="sans-serif" size="+1">
            <CENTER><B>boodschap voor deze dag</B></CENTER>
            </FONT>
            </TD>
            </TR>
            <TR>
            <TD>
            <!-- weblogin: motd start -->
        <p>
```

**Comment by jovanbulck** [comment]
nice ;-)

maybe -- just an idea -- we can auto retry once when receiving this error (as it is server side and may not happen again...)

**Comment by GijsTimmers** [comment]
I'd say no: it will probably make the code a lot more complicated.

My proposal: print some sort of a 'Try again' error message.

**Comment by jovanbulck** [comment]
Yes you're right I think it would indeed mess up the code base too much

We should probably throw a custom exception on this err code in the browser and catch it in the [worker](https://github.com/GijsTimmers/kotnetcli/blob/dev/kotnetcli/worker.py) as is done with the wrong credentials case...

**Comment by GijsTimmers** [comment]
Yes, that will work, too.

**Comment by jovanbulck** [comment]
done!

From the commit msg:

Added a handler for rccode 301: internal server side script error
and support for simulating *any* rccode number in the kotnetcli_test
front end through overriding the -i cmd line option with an optional
argument

example usage:

kotnetcli_test -i 301
kotnetcli_test -i 211
kotnetcli_test -i 100
kotnetcli_test -i 101
