### ISSUE TITLE
Writing the app in Java instead of Python

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#83]
Up until now, the mobile app has been written in a combination of both Python and Kivy.

Programming, and especially compiling in Kivy has been a pain from the get-go. That's why I propose to write the app in Java from now on.

The disadvantage of doing so is that this will inevitably lead to a duplication of code. But I do see this as the way forward:

- Easy compiling (this is a big one)
- Fully native Android code and GUI
- No loading screen and delay when starting the app
- No cluttering of the `kotnetcli` directory with Kivy stuff

There will probably be some roadblocks up ahead, but nonetheless, I see a bright future for `kotnetcli`.

**Comment by jovanbulck** [comment]
Good decision! Let's clean up the Kivy mess and move towards a stable `kotnetcli` release :)

**Comment by GijsTimmers** [comment]
a1884b307def170c99df9da0644d952f17caae27; 18e70e866274f862d7404eceee87f4bd718de8c9
