### ISSUE TITLE
Add valid kotnet institution choices

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/kotnetcli#87]
We should figure out and add all valid kotnet institution choices, so the user can login to the institution of his/her choice via `kotnetcli --institution=CHOICE`

This is probably possible by manually choosing each institution in the list on `netlogin.kuleuven.be` and then looking at the `inst=` value in the URL (?) I cannot do this, as  my browser gets redirected to `?inst=kuleuven-campusnet`, without being offered an institution choice...

Add the relevant names in the array on line 116 in `kotnetcli.py` on `dev` branch:

```python
        choices=[ 'kuleuven', 'kuleuven-campusnet'],
```

**Comment by GijsTimmers** [comment]
Associatie KU Leuven: https://netlogin.kuleuven.be/cgi-bin/wayf2.pl?inst=kuleuven&lang=nl&submit=Ga+verder+%2F+Continue

Kotnet Extern: https://netlogin.kuleuven.be/cgi-bin/wayf2.pl?inst=kotnetext&lang=nl&submit=Ga+verder+%2F+Continue

I don't see any other institutions. Are there any?

**Comment by jovanbulck** [comment]
> I don't see any other institutions. Are there any?

No idea. Maybe you could ask around for KH Leuven?

**Comment by GijsTimmers** [comment]
I will just close this one until other institutions appear.
