### ISSUE TITLE
Better exception handling

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#9]
We should cover, if possible:
- [x] KeyboardInterrupts
- [x] Invalid username/password combination
- [x] Kotnet server unreachable (timeout)
- [x] Kotnet server unreachable (due to being at home)
- [x] Kotnet server unreachable (faulty internet connection)
- [x] Dependencies not installed (ImportError)
- [x] Everything OK, yet not being able to log in due to KotNet restrictions (hard to implement, more testing needed)

**Comment by jovanbulck** [comment]
Current status the `dev` branch:

- `LoginWorker` catches (specific) exceptions from the `KotnetBrowser` class to fail gracefully; this covers the items marked above

We should still cover:

- Import exceptions, this should go together with logger info (as in `Coloramacommunicator`)

```python

try:
   logger.debug("Probeert Colorama te importeren..."),
   from colorama import ( ## Voor gekleurde tekst.
                        Fore,
                        Style,
                        init as colorama_init
                        )
    logger.debug("OK")
except ImportError:
     logger.error("Couldn't import the colorama library.")
     pass # we probably want to exit(FAILURE) here
```

- Keyboard and other unexpected exceptions; we could write something as (in `kotnetcli.py`): 

```python

## Start de zaak asa deze file rechtstreeks aangeroepen is vanuit
## command line (i.e. niet is geimporteerd vanuit een andere file)
if __name__ =='__main__':
try:
   k = KotnetCLI()
   k.parseArgumenten()
except Exception, e:
   print "blabla: %s" % e

```

possible problem however, is that when a communicator is already started, it is not terminated correctly with `beeindig_sessie()`, so then we should also make sure we catch KeyboardExceptions in the worker (as is for example not done in `login_resultaten()` now)

**Comment by jovanbulck** [comment]
> Everything OK, yet not being able to log in due to KotNet restrictions (hard to implement, more testing needed)

@GijsTimmers  What do you mean here? Is this handled in the `dev` branch now?

**Comment by GijsTimmers** [comment]
Can't remember...

**Comment by jovanbulck** [comment]
> Can't remember...

:D I mark it done then; two more to go...

**Comment by GijsTimmers** [comment]
Getting there... 

I see that the `KeyboardInterrupt` is not implemented yet. The best bet to implement this would probably be the way it's done in youtube-dl: [a try-except mechanism in the main()](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/__init__.py#L413). I've just added a separate `main()` (see: 9445aa8bfcbbced068c43b2ba389e2948460af0f) , so that would be relatively easy to implement.

**Comment by jovanbulck** [comment]
> try-except mechanism in the main()

Nice, this is indeed the best way to handle `KeyboardInterrupt`

**Comment by jovanbulck** [comment]
I tried adding 

```python
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        logger.debug("Keyboard interrupt received")
        sys.exit(EXIT_FAILURE)
```

But we still need **fine grained exception catching in the worker**, eg:

```python
def netlogin(self, co):
        co.eventNetloginStart()
        try:
            self.browser.login_open_netlogin()
            co.eventNetloginSuccess()
        except:
            ## the exception should be fine grained here...
            co.eventNetloginFailure()
            co.beeindig_sessie(EXIT_FAILURE)
            sys.exit(EXIT_FAILURE)
```

**Comment by GijsTimmers** [comment]
You're absolutely right about this.

**Comment by jovanbulck** [comment]
`worker` needs to print the traceback on unexpected exceptions in the `browser`; something like

``` python
    def netlogin(self, co):
        co.eventNetloginStart()
        try:
            self.browser.login_open_netlogin()
            co.eventNetloginSuccess()
        except Exception, e:
            co.eventNetloginFailure()
            co.beeindig_sessie(EXIT_FAILURE)
            logger.error("fatal exception '%s' with traceback:" % e)
            traceback.print_exc()
            sys.exit(EXIT_FAILURE)
```

**Comment by jovanbulck** [comment]
Done: KeyboardInterrupts

#106 uses the Python [atexit](https://docs.python.org/2/library/atexit.html) module to ensure  `eventExit()` method of the running communicator is always called. This nicely allows a communicator to restore user interface elements (e.g. draw cursor), even in the presence of asynchronous keyboard interrupts.

We thus only still need to handle import exceptions.

**Comment by jovanbulck** [comment]
Done: ImportErrors

```
The lazy importing mechanism only imports a communicator when it has been
requested by the front-end, via the fabriek. This ensures an end-user
does not have to install all the dependencies for all the communicators
in order to run kotnetcli. The front-end is thus responsible to catch
any ImportErrors thrown at communicator creation time.

This nicely maintains the behavior that *only* the front-end and the
communicators encapsulate user interaction + only the front-end or
worker may terminate (sys.exit) the program.
```
