### ISSUE TITLE
Please test the new requests library setup on campusnet

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#92]
73c267c3f5b123cbeb009433be2555bcda94f5d6: `kotnetcli` uses `requests` instead of `mechanize` from now on. I believe that this is a good decision. However, we need to test whether the current setup works on other networks as well (e.g. campusnet). Will you do this, @jovanbulck?

**Comment by jovanbulck** [comment]
All is well on `--institution kuleuven-campusnet` :-)

**Comment by GijsTimmers** [comment]
Thank you!
